### ISSUE TITLE
Baseline Grid

### ISSUE THREAD

**Issue by CCucalonUTA** [whoistobias/ctec3350#3]
Could you please review this file and commit updates?

**Comment by CCucalonUTA** [comment]
The baseline grid file is still off. Could you please review it?

You can still turn it in tonight for a grade of 80 this evening.

Thank you,

Carlos

**Comment by whoistobias** [comment]
It appears my link to the css file was bad. It's been fixed, although I don't remember how it got that way.

**Comment by CCucalonUTA** [comment]
It's looking a bit better, but the text is still not aligning to the baseline grid.

Could you take a look at it?

Thank you!

**Comment by whoistobias** [comment]
This was fixed about a week ago.
